# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: codyloyd/author-site
  branch: main
  identity_url: https://auth.decapbridge.com/sites/b02af666-8e64-44e1-bc7e-61a567225fee
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://codyloyd-author-site.netlify.app

media_folder: "public/images/" # Where to store media assets
public_folder: "/images/" # URL prefix for media assets

collections:
  - name: "stories" # Used in routes, ie.: /admin/collections/stories
    label: "Stories" # Used in the UI
    folder: "stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., "my-story"
    fields:
      - {name: "layout", label: "Layout", widget: "hidden", default: "story.html"}
      - {name: "title", label: "Title", widget: "string"}
      - {name: "date", label: "Date", widget: "datetime", default: '{{now}}'}
      - {name: "coverImage", label: "Cover Image", widget: "image"}
      - {name: "pinOrder", label: "Pin Order", widget: "number", required: false}
      - {name: "description", label: "Description", widget: "text", required: false}
      - {name: "body", label: "Body", widget: "markdown"}